export const homeObjOne = {
  id: 'First',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Nov.11: ',
  headline: 'Spider Plant',
  description:
    'Attributes go here',
  buttonLabel: 'Match projects with the Spider Plant',
  imgStart: true,
  img: require('../plant_of_the_day/Images/Spider-Plant.jpeg'),
  alt: 'Car',
  dark: false,
  primary: false,
  darkText: true,
  imageSrc: require("../plant_of_the_day/Images/support-icon.svg"),
  title1: "Water",
  descriptions1: "2/Week",
  title2: "Light",
  descriptions2: "Full",
  title3: "Temperature",
  descriptions3: "60F~80F",
  title4: "Site",
  descriptions4: "Bedroom",
  title5: "Toxicity",
  descriptions5: "None",
  title6: "Difficulty",
  descriptions6: "Easy", 
};

export const homeObjTwo = {
  id: 'Second',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Nov.10',
  headline: 'Aloe Vera',
  description:
    'Attributes go here',
  buttonLabel: 'Match projects with the Aloe Vera',
  imgStart: false,
  img: require('../plant_of_the_day/Images/Aleo-Vera.jpeg'),
  alt: 'Piggybank',
  dark: true,
  primary: true,
  darkText: false,
  imageSrc: require("../plant_of_the_day/Images/support-icon.svg"),
  title1: "Water",
  descriptions1: "2/Week",
  title2: "Light",
  descriptions2: "Full",
  title3: "Temperature",
  descriptions3: "60F~80F",
  title4: "Site",
  descriptions4: "Bedroom",
  title5: "Toxicity",
  descriptions5: "None",
  title6: "Difficulty",
  descriptions6: "Easy", 
};

export const homeObjThree = {
  id: 'Third',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Nov.9',
  headline: 'Lavender Tree',
  description:
    'Attributes go here',
  buttonLabel: 'Match projects with the Lavender Tree',
  imgStart: true,
  img: require('../plant_of_the_day/Images/Lavender-Tree.jpeg'),
  alt: 'Car',
  dark: false,
  primary: false,
  darkText: true,
  imageSrc: require("../plant_of_the_day/Images/support-icon.svg"),
  title1: "Water",
  descriptions1: "2/Week",
  title2: "Light",
  descriptions2: "Full",
  title3: "Temperature",
  descriptions3: "60F~80F",
  title4: "Site",
  descriptions4: "Bedroom",
  title5: "Toxicity",
  descriptions5: "None",
  title6: "Difficulty",
  descriptions6: "Easy", 
};

export const homeObjFour = {
  id: 'Fourth',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Nov.8',
  headline: 'Mojito Mint',
  description:
    "Attributes go here",
  buttonLabel: 'Match projects with the Mojito Mint',
  imgStart: false,
  img: require('../plant_of_the_day/Images/Mojito-Mint.jpeg'),
  alt: 'Papers',
  dark: true,
  primary: true,
  darkText: false,
  imageSrc: require("../plant_of_the_day/Images/support-icon.svg"),
  title1: "Water",
  descriptions1: "2/Week",
  title2: "Light",
  descriptions2: "Full",
  title3: "Temperature",
  descriptions3: "60F~80F",
  title4: "Site",
  descriptions4: "Bedroom",
  title5: "Toxicity",
  descriptions5: "None",
  title6: "Difficulty",
  descriptions6: "Easy", 
};
